graph_ql:
    schema_class: "AppBundle\\GraphQL\\Schema"

overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: ~

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BlankAdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:
            contexts:   [admin]
        sonata.block.service.rss:
            contexts:   [admin]

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

        # Some block with different templates
        #acme.demo.block.demo:
        #    templates:
        #       - { name: 'Simple', template: 'AcmeDemoBundle:Block:demo_simple.html.twig' }
        #       - { name: 'Big',    template: 'AcmeDemoBundle:Block:demo_big.html.twig' }




sonata_admin:
    title:      Acme
    title_logo: bundles/app/images/link-arrow.png
    security:
        # the default value
        handler: sonata.admin.security.handler.noop
        # use this service if you want ACL
        handler: sonata.admin.security.handler.noop
    options:
        form_type: standard
    dashboard:
         blocks:
              -
                  position: left
                  type: sonata.admin.block.admin_list
              -
                  position: right
                  type: sonata.block.service.text
                  settings:
                      content: >
                          <h2>Welcome to the Sonata Admin</h2>
                          <p>This is a <code>sonata.block.service.text</code> from the Block
                          Bundle, you can create and add new block in these area by configuring
                          the <code>sonata_admin</code> section.</p> <br /> For instance, here
                          a RSS feed parser (<code>sonata.block.service.rss</code>):
              -
                  position: right
                  type: sonata.block.service.rss
                  #roles: [POST_READER]
                  settings:
                      title: Sonata Project's Feeds
                      url: https://sonata-project.org/blog/archive.rss
         groups:
            app.admin.group.content:
                label: app.admin.group.content
                label_catalogue: AppBundle
                items:
                    - admin.blog_post
                    - admin.category
                    - admin.product
            app.admin.group.misc: ~

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
  dbal:
    default_connection:  default
    connections:
      default:
        driver:   pdo_sqlite
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%database_path%"

      development:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8


  orm:
    default_entity_manager: development
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.default
        #auto_mapping: true
        #mappings:
        #  AppBundle: ~
      development:
        #auto_mapping: true
        mappings:
          AppBundle: ~
        connection: development
    auto_generate_proxy_classes: "%kernel.debug%"

doctrine_mongodb:
    default_commit_options: ~
    auto_generate_proxy_classes:  false
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                #persist: true
                #timeout:              ~
                #replicaSet: relica0
    default_database: test_database
    document_managers:
        default:
            metadata_cache_driver: array
            #auto_mapping: true
            mappings:
              AppBundle:
                type: annotation
                dir: Document
              BlankAdminBundle:
                type: annotation
                dir: Document
                #prefix: 'AcmeStoreBundle:Entity'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
