imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BlankAdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title:      Acme
    title_logo: bundles/app/images/link-arrow.png
    security:
        # the default value
        handler: sonata.admin.security.handler.noop
        # use this service if you want ACL
        handler: sonata.admin.security.handler.noop
    options:
        form_type: standard
    dashboard:
         groups:
            app.admin.group.content:
                label: app.admin.group.content
                label_catalogue: AppBundle
                items:
                    - admin.blog_post
                    - admin.category
            app.admin.group.misc: ~


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
  dbal:
    default_connection:  default
    connections:
      default:
        driver:   pdo_sqlite
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%database_path%"

      development:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8


  orm:
    default_entity_manager: development
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.default
        #auto_mapping: true
        #mappings:
        #  AppBundle: ~
      development:
        #auto_mapping: true
        mappings:
          AppBundle: ~
        connection: development
    auto_generate_proxy_classes: "%kernel.debug%"

doctrine_mongodb:
    default_commit_options: ~
    auto_generate_proxy_classes:  false
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                #persist: true
                #timeout:              ~
                #replicaSet: relica0
    default_database: test_database
    document_managers:
        default:
            metadata_cache_driver: array
            #auto_mapping: true
            mappings:
              BlankAdminBundle:
                type: annotation
                dir: Document
                #prefix: 'AcmeStoreBundle:Entity'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
