services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, AppBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category}
        calls:
            - [ setTranslationDomain, [AppBundle]]

    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog post}
        calls:
            - [ setTranslationDomain, [AppBundle]]
